DROP TABLE IF EXISTS `connections`;
DROP TABLE IF EXISTS `dogs`;
DROP TABLE IF EXISTS `address`;
DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `STATUS` VARCHAR(8) NOT NULL,  
  `TYPE` VARCHAR(8) NOT NULL,  
  `USERNAME` VARCHAR(64) NOT NULL,
  `PASSWORD` VARCHAR(128) NOT NULL,
  `KENNEL_NAME` VARCHAR(128) DEFAULT NULL,
  `NAME` VARCHAR(128) NOT NULL,
  `DESCRIPTION` LONGTEXT,
  `EMAIL` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `USERNAME` (`USERNAME`),
  UNIQUE KEY `KENNEL_NAME` (`KENNEL_NAME`),  
  UNIQUE KEY `EMAIL` (`EMAIL`) 
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `address` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `BREEDER_ID` INT(11) NOT NULL,
  `COUNTRY` VARCHAR(64) NOT NULL,
  `CITY` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FKBB979BF4DB907E22` (`BREEDER_ID`),
  CONSTRAINT `FKBB979BF4DB907E22` FOREIGN KEY (`BREEDER_ID`) REFERENCES `users` (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `dogs` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `STATUS` VARCHAR(16) NOT NULL,
  `BREEDER_ID` INT(11) NOT NULL,  
  `BREAD` VARCHAR(128) NOT NULL,
  `NAME` VARCHAR(128) NOT NULL,  
  `FOR_SALE` TINYINT(1) NOT NULL,
  `GENDER` VARCHAR(8) NOT NULL,
  `DOB` DATE NOT NULL,
  `DESCRIPTION` LONGTEXT,
  `FATHER_ID` BIGINT(20) DEFAULT NULL,
  `MOTHER_ID` BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK2F22B7DB907E22` (`BREEDER_ID`),
  KEY `FK2F22B74ED1E6FC` (`FATHER_ID`),
  KEY `FK2F22B7B016435` (`MOTHER_ID`),
  CONSTRAINT `FK2F22B7B016435` FOREIGN KEY (`MOTHER_ID`) REFERENCES `dogs` (`ID`),
  CONSTRAINT `FK2F22B74ED1E6FC` FOREIGN KEY (`FATHER_ID`) REFERENCES `dogs` (`ID`),
  CONSTRAINT `FK2F22B7DB907E22` FOREIGN KEY (`BREEDER_ID`) REFERENCES `users` (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `connections` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `STATUS` VARCHAR(16) NOT NULL,
  `DOG_ID` BIGINT(20) NOT NULL,
  `BREEDER_ID` INT(11) NOT NULL,
  `BUYER_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK66CB5D55DB907E22` (`BREEDER_ID`),
  KEY `FK66CB5D558B8FB450` (`BUYER_ID`),
  KEY `FK66CB5D55E09D5B1C` (`DOG_ID`),
  CONSTRAINT `FK66CB5D55E09D5B1C` FOREIGN KEY (`DOG_ID`) REFERENCES `dogs` (`ID`),
  CONSTRAINT `FK66CB5D558B8FB450` FOREIGN KEY (`BUYER_ID`) REFERENCES `users` (`ID`),
  CONSTRAINT `FK66CB5D55DB907E22` FOREIGN KEY (`BREEDER_ID`) REFERENCES `users` (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;